### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by prolificcoder** [appium/appium-android-driver#122]
I am trying to figure out how to run E2E/functional tests, can someone point me at right direction?

`gulp once - only ran unit tests`

`gulp e2eTest didn't work`

I made partial progress by first
`gulp transpile`

and the `mocha build/path/to/testfile` but it failed with lack of correct timeout

```
  1) Find - basic "before all" hook: callee$1$0:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by imurchie** [comment]
`gulp e2e-test` ought to run `gulp transpile` as part of its flow.

Can you run `_FORCE_LOGS=1 gulp e2e-test` and post the output in a gist here?

**Comment by trevren11** [comment]
@prolificcoder I had this problem, and it was because I had my node server running.
