### ISSUE TITLE
How can I tell if a commit is in a particular version of Appium?

### ISSUE THREAD

**Issue by amaharana** [appium/appium-android-driver#124]
I am looking at #83. By examining the date and tags on the associated commit I can make a fair guess about the Appium version this commit is in. But is there a command to achieve the same? I tried `git branch -a -contains 6a048ef386aae3b2200648a16c7922dcd7d42cb3` but that doesn't help get Appium version numbers. Any idea?

**Comment by imurchie** [comment]
There is, unfortunately, no automated way to say. You can look in the Appium release for the `npm-shrinkwrap.json` file, which will specify the exact version of the `appium-android-driver` that is being used, and then check whether the particular commit is in that version.
