### ISSUE TITLE
setcontext throws error when available contexts are only NATIVE_APP and CHROMIUM

### ISSUE THREAD

**Issue by rkavalap** [appium/appium-android-driver#143]
Hybrid app based app using crosswalk web driver. Testing on real devices. 
Works with appium 1.3.5 with crosswalk web driver. 

Latest version 1.5.2 throws error.  
Based on investigation 
Latest version throws NoSuchContextError() 

If the available contexts are only NATIVE_APP, CHROMIUM, I would expect the defaults to be chosen from one of them instead of WEBVIEW_{apppackage}. 

v1.3.5 was exiting gracefully 
return cb(null, {
        status: status.codes.NoSuchContext.code
      , value: "Context '" + name + "' does not exist"
 });

code paths where it's called

this.defaultWebviewName called from initautowebview  (lib/driver.js) - line no 202
The above line is based on appium server flags autowebview (true, false)

this.defaultWebviewName called from setcontext (lib/commands/context.js) - line no 39 
function itself is present in context.js at line no 89

**Comment by imurchie** [comment]
Can you provide the full server logs? We don't have enough information to go on at the moment.

**Comment by rkavalap** [comment]
@imurchie 
appium v1.5.2 log 
I added a logging statement before android driver shutdown. 
https://gist.github.com/rkavalap/57e6592b466dc1e9d92bbb03cc17090b

**Comment by rkavalap** [comment]
This bug is related to and should get fixed with
https://github.com/appium/appium/issues/4597
