### ISSUE TITLE
setGeoLocation returns random info

### ISSUE THREAD

**Issue by imurchie** [appium/appium-android-driver#144]
The spec says we should be returning the location. If it is not possible in our new scheme to find the actual location, we should, if there is no error in setting, return the location that was requested.

**Comment by imurchie** [comment]
The problem is here: https://github.com/appium/appium-android-driver/blob/master/lib/commands/network.js#L82

Rather than returning the value form the `adb` call, we should be awaiting that and returning other information.

**Comment by rkavalap** [comment]
Issue moved to [appium/appium #7400](https://github.com/appium/appium/issues/7400) via [**ZenHub**](https://www.zenhub.com/)
