### ISSUE TITLE
1.5 Cleanup - phase 1

### ISSUE THREAD

**Issue by scottdixon** [appium/appium-android-driver#34]
- Make sure dependencies are up to date. **Waiting for beta tag on appium-adb package**
- Remove unused dependencies. **Done**
- Review TODOs and see if we need to resolve any before release. **In Progress**
- Ensure code conforms to style guide. **Done**
- Ensure we're not using any sync functions. **Filed issue for AdmZip module**

**Comment by scottdixon** [comment]
## Current TODOs ##
- **commands.keyevent:** Deprecate keyevent; currently wd only implements keyevent.
- **commands.getStrings:** This is mutating the current language, but it's how appium currently works.
- **commands.toggleFlightMode:** Implement isRealDevice() to throw a NotYetImplementedError.
- **commands.setGeoLocation:** Implement isRealDevice() to throw a NotYetImplementedError.
- **helpers.doKey:** Confirm we need this delay. Seems to work without it.
- **commands.doTouchAction:** Clarify behavior of 'cancel' action and fix this.
- **commonCapConstraints:** Add documentation for recreateChromeDriverSessions.
- **createSession:** Fail if app file is missing, or if app is not on the device?
- **createSession:** Extend the validation function to prove that we always either have browserName or app, so we don't have to throw an error if neither of these conditions is met. Also need to make sure we don't have BOTH app and browserName.
- **webviewsFromProcs:** Some of this function belongs in appium-adb.
- **procFromWebview:** This should be called procFromPid and exist in appium-adb.

@jlipps @moizjv @imurchie @Jonahss - Let's kick off a discussion on which TODOs need to be resolved for the release. I guess the question is: can any of the above TODOs wait?

**Comment by imurchie** [comment]
- **commands.keyevent**: I think we should do the deprecation warning. However, this ought to be done at the protocol level, when we dispatch the method (perhaps we need a flag in the routes, for `deprecated`?)
- **commands.getStrings**: Not sure what the message means. 
- **commands.toggleFlightMode**: Should be done. Failing slowly is a bad option.
- **commands.setGeoLocation**: Ditto.
- **helpers.doKey**: Seems low priority. We could make an issue to investigate.
- **commands.doTouchAction**: Again, I think this should be made into an issue to be investigated later. We're going to have to rethink the gesture API in light of spec changes anyway. `cancel` might make more sense, or not even be there.
- **commonCapConstraints** Yes, we need documentation.
- **createSession**: Not sure about first one, more info? Second, yes. See how it is done in `appium-ios-driver`.
- **webviewsFromProcs**: We should do, but can put it low in the queue.
- **procFromWebview**: Ditto.

**Comment by scottdixon** [comment]
doKey delay was introduced here: https://github.com/appium/appium/commit/1b488f74e0bb7655e4eaba6a6b08b8c15b10aa35
