### ISSUE TITLE
activate app  turns on auto rotate in android

### ISSUE THREAD

**Issue by Abhinav-Anand-Lambdatest** [appium/appium-android-driver#738]
driver.activate_app turns on  auto rotation. 
https://stackoverflow.com/questions/56684778/adb-shell-monkey-command-changing-device-orientation-lock

**Comment by KazuCocoa** [comment]
Thank you, we can address it in the code's docstring and doc.

https://github.com/appium/appium-uiautomator2-driver/#mobile-startactivity can explicitly start an activity via `am start`

**Comment by KazuCocoa** [comment]
I appended it in the doc, thank you.
