### ISSUE TITLE
Issues with select date from the datepicker with Appium for Android Driver

### ISSUE THREAD

**Issue by niranjanparija** [appium/appium-android-driver#91]
Hi,I am facing issues to select date from the datepicker with Appium for Android Driver.Please check the attached screenshots of the Calender I am looking for.

I have already tried with element.clear() followed by element.sendkeys("text"),but its not working.

Also I tried to work with Scroll to followed by TouchAction ,where its working till selecting the Year ,but after that its failed to select the date and month which should be selected from the screenshot named as DatePicker2.

Can anyone please suggest me any workout .
![daypicker1](https://cloud.githubusercontent.com/assets/16086474/12818547/41dde152-cb4f-11e5-9103-f1730b1f3080.PNG)
![daypicker2](https://cloud.githubusercontent.com/assets/16086474/12818552/44d5feee-cb4f-11e5-9815-92a7aa436885.PNG)
![daypicker3](https://cloud.githubusercontent.com/assets/16086474/12818554/472640aa-cb4f-11e5-8b72-fec568533c5f.PNG)

**Comment by niranjanparija** [comment]
Can anyone please suggest on this ,how to tackle the issue.So far tried with all the possible options like DatePicker,Number Picker with Xpath,Class,SendKeys,Scroll To and unfortunately nothing works so far.

**Comment by niranjanparija** [comment]
Facing the same issue with attached calender also.
![2nd calender](https://cloud.githubusercontent.com/assets/16086474/12851266/dc8d993c-cc20-11e5-8ca0-4d1dbc1f7620.PNG)

**Comment by niranjanparija** [comment]
@TikhomirovSergey - can you please guide on this issue

**Comment by rkavalap** [comment]
Issue moved to [appium/appium #7398](https://github.com/appium/appium/issues/7398) via [**ZenHub**](https://www.zenhub.com/)

**Comment by joshidipakkumar** [comment]
for all the user who are still finding the way to select date can use below code. I am using this code and working perfectly for me. It will work for 2nd screenshot attached by rkavalap.



do {                 
WebElement source =   driver.findElement(By.xpath("//android.view.View[@instance='0']"));        WebElement destination =   driver.findElement(By.xpath("//android.view.View[@instance='22']"));           TouchAction action = new   TouchAction((PerformsTouchActions)driver);        System.out.println("Dragging   item");        action.longPress(source).moveTo(destination).release().perform();        

boolean bul =   driver.findElementsByXPath("//android.view.View[@content-desc='24   January 2017']").isEmpty();     

  } while(bul!=false);                

driver.findElementByAccessibilityId("24 January   2017").click();
![androidcalendar](https://user-images.githubusercontent.com/33867053/41717068-242a483e-7576-11e8-8607-a08799291e88.PNG)
-----------------------------------------------------------------------------------------------------------------
I used drag and drop touch action to scroll and this will scroll uptill given date is not found.
