### ISSUE TITLE
TouchAction.perform() The operation is ineffective

### ISSUE THREAD

**Issue by haopizi** [appium/appium-android-driver#962]
Code:
Duration duration = Duration.ofMillis(500);
TouchAction action1 = new TouchAction(driver).press(PointOption.point(startx, starty)).waitAction(WaitOptions.waitOptions(duration)).moveTo(PointOption.point(endx, endy)).release();
action1.perform();

The logs returned by the device：
![image](https://github.com/user-attachments/assets/ec54b075-abc4-48b1-b11e-58dc300afd02)

The device's screen can slide, but there is no response after the action1.performang() operation
Why did this situation occur?

**Comment by KazuCocoa** [comment]
I guess your case was for https://github.com/appium/appium-uiautomator2-driver/blob/master/CHANGELOG.md#features-8

The endpoint has been deprecated. Please use w3c actions with latest Appium. If you're interested in how to actions work, https://github.com/appium/appium-uiautomator2-driver/blob/a3f32360bd6c53ffcaed820257d5d9d1f313707f/docs/actions.md will also helps then.
